name: Development build (SpeedUp)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches-ignore:
      - 'l10n_main'
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'l10n_main'
  workflow_dispatch:

jobs:
  build:
    name: Development build
    strategy:
      matrix:
        include:
          - platform: 2
            platform_name: ios

    runs-on: macos-14

    steps:
      - name: Show available Xcode and select a suitable one
        run: |
          set -e
          echo "Available apps in /Applications (matching Xcode*):"
          ls /Applications | grep -E "Xcode(.+)?\.app" || true
          if [ -d "/Applications/Xcode_16.app" ]; then
            echo "Selecting /Applications/Xcode_16.app"
            sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
          elif [ -d "/Applications/Xcode_15.app" ]; then
            echo "Selecting /Applications/Xcode_15.app"
            sudo xcode-select -s /Applications/Xcode_15.app/Contents/Developer
          elif [ -d "/Applications/Xcode.app" ]; then
            echo "Selecting /Applications/Xcode.app"
            sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          else
            echo "No matching Xcode found under /Applications. Leaving system default."
          fi
          xcodebuild -version || true
          xcrun simctl list runtimes || true

      - name: Checkout repository (with submodules)
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: |
          echo "sha=$(git ls-remote https://github.com/AngleAuraMC/gl4es-114-extra refs/heads/master | grep -io '^\S*')" >> $GITHUB_OUTPUT

      - name: Restore ccache
        uses: actions/cache@v4
        id: ccache
        with:
          path: |
            ~/.ccache
          key: ccache-${{ runner.os }}-${{ matrix.platform_name }}-${{ hashFiles('**/Makefile', '**/*.c', '**/*.m', '**/*.mm', '**/*.cpp', '**/*.h') }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ matrix.platform_name }}-

      - name: Restore build cache
        uses: actions/cache@v4
        id: build-cache
        with:
          path: |
            build
            artifacts
          key: build-${{ runner.os }}-${{ matrix.platform_name }}-${{ hashFiles('**/Makefile', '**/*.mk') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.platform_name }}-

      - name: Restore gl4es cache
        uses: actions/cache@v4
        id: gl4es-cache
        with:
          path: gl4es/libs
          key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}
          restore-keys: |
            gl4es-holy-ios-shared-2-


      - name: Install tools (brew: make, ldid, ccache) and configure ccache
        run: |
          set -e
          brew update
          brew install make ldid ccache || true
          if [ -d "/opt/homebrew/opt/ccache/libexec" ]; then
            export PATH="/opt/homebrew/opt/ccache/libexec:$PATH"
          elif [ -d "/usr/local/opt/ccache/libexec" ]; then
            export PATH="/usr/local/opt/ccache/libexec:$PATH"
